version: "3.9"
services:
  db-postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"      
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 

  db-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "82:80"
    depends_on:
      - db-postgres

  web: 
    restart: "always"    
    volumes:
      - ./cars-app:/app
      - ./static:/static
    env_file:
      - ./cars-app/.env
    build:
      context: .      
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - web      
    volumes:
      - ./static:/www/static
    links:
      - web:web   

volumes:
  web-static: